environment:
deployment:
  name: icap-management-ui
  port: 8080
service:
  name: icap-management-ui-service
  port: 80
imagestore:
  icapmanagementui:
    repository: glasswallsolutions/icap-management-ui
    tag: dev-latest
config:
  transactionEventApiUrl: https://transaction-query-aggregator/api/v1
  policyManagementApiUrl: https://policy-management-api/api/v1
