environment:
deployment:
  name: icap-management-ui
  port: 8080
service:
  name: icap-management-ui-service
  port: 80
imagestore:
  icapmanagementui:
    repository: glasswallsolutions/icap-management-ui
    tag: dev-latest
config:
  transactionEventApiUrl: http://transactioneventapi.transaction-event-api.svc.cluster.local/api/v1
  policyManagementApiUrl: http://policymanagementapi.policy-management-api.svc.cluster.local/api/v1
