environment:
deployment:
  name: icap-management-ui
  port: 8080
service:
  name: icap-management-ui-service
  port: 80
ingress:
  name: icap-management-ui-ingress
  port: 80
  host: management-ui.northeurope.cloudapp.azure.com
  path: /(.*)
imagestore:
  icapmanagementui:
    repository: glasswallsolutions/icap-management-ui
    tag: dev-latest
config:
  transactionEventApiUrl: https://transaction-query-aggregator/api/v1
  policyManagementApiUrl: https://policy-management-api/api/v1
secrets:
  tlsCrt: "<<https://icap-neu-keyvault.vault.azure.net/secrets/management-ui-cert/2cc07447a95e4dd4af42d9d5d5fdfc54>>"
  tlsKey: "<<https://icap-neu-keyvault.vault.azure.net/secrets/management-ui-tls-key/fe8f7d162d294f48aa29a1c34765c205>>"
