{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: management-ui-registry-credential
data:
  .dockerconfigjson: {{ .Values.secrets.containerregistry.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end }}