apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: icap-management-ui
          image: glasswallsolutions/icap-management-ui:main-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.deployment.port }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
