{{- if .Values.secrets }}
{{- if .Values.secrets.managementui }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:  
  tls.crt: {{ .Values.secrets.managementui.tlsCrt }}
  tls.key: {{ .Values.secrets.managementui.tlsKey }}
{{- end }}
{{- end }}