export const CHANGE_PAGE_TITLE = "CHANGE_PAGE_TITLE";

export const TOGGLE_NAV_EXPANDED = "TOGGLE_NAV_EXPANDED";

export const RESET_STATE = "RESET_STATE";

// Root
export const SET_VERSION = "SET_VERSION";

// Analytics
export const UPDATE_ANALYTICS_TIME_FILTER = "UPDATE_ANALYTICS_TIME_FILTER";

// Request History
export const ADD_FILTER_FROM_CHECKBOXES = "ADD_FILTER_FROM_CHECKBOXES";
export const ADD_FILTER_FROM_INPUT = "ADD_FILTER_FROM_INPUT";
export const REMOVE_FILTER = "REMOVE_FILTER";
export const UPDATE_REQUEST_HISTORY_TIME_FILTER = "UPDATE_REQUEST_HISTORY_TIME_FILTER";

// Policy
export const SET_POLICY_ERROR = "SET_POLICY_ERROR";
export const SET_STATUS = "SET_STATUS";
export const SET_IS_POLICY_CHANGED = "SET_IS_POLICY_CHANGED";
export const SET_CURRENT_POLICY = "SET_CURRENT_POLICY";
export const SET_DRAFT_POLICY = "SET_DRAFT_POLICY";
export const SET_POLICY_HISTORY = "SET_POLICY_HISTORY";
export const SET_NEW_DRAFT_POLICY = "SET_NEW_DRAFT_POLICY";
export const CANCEL_DRAFT_CHANGES = "CANCEL_DRAFT_CHANGES";
export const SET_POLICY_HISTORY_PAGINATION = "SET_POLICY_HISTORY_PAGINATION";

// Users
export const SET_USER_ERROR = "SET_USER_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USERS = "SET_USERS";
export const SET_UPDATED_USERS = "SET_NEW_USERS";
export const SET_USERS_HAVE_CHANGES = "SET_USERS_HAVE_CHANGES";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";
export const ADD_NEW_USER = "ADD_NEW_USER";
export const DELETE_NEW_USER = "DELETE_NEW_USER";
export const EDIT_NEW_USER = "EDIT_NEW_USER";
export const SAVE_USERS_CHANGES = "SAVE_USERS_CHANGES";
export const CANCEL_USERS_CHANGES = "CANCEL_USERS_CHANGES";