name: CD QA
env:
  REPOSITORY: glasswallsolutions
  IMAGE: icap-management-ui
  TAG: qa
on:
  push:
    branches: [qa]

jobs:
  build-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: icapserviceaccount
          password: ${{ secrets.ICAPDOCKERSECRET }}
      - name: Build and Push Docker Image
        run: |
          docker build -f server/Dockerfile -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-${GITHUB_SHA::7} -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-latest .
          docker push ${{ env.REPOSITORY }}/${{ env.IMAGE }}